name: Deploy Next.js Project to CPanel
on:
  push:
    branches:
      - main # Deploy on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify the Node.js version

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      # Step 4: Build the Project
      - name: Build Project
        run: |
          npm install --legacy-peer-deps
        env:
          PORT: 5000
          BASE_URL: http://localhost:5555
          DATABASE_URL: "mysql://awrasaix_mallspot:mallspot@123@91.204.209.22:3306/awrasaix_mallspot:?schema=public"
          JWT_SECRET: tsgedTsehay

      # Step 5: Prepare Deployment Package
      - name: Copy Files to Temporary Directory
        run: rsync -a . /tmp/deployment-copy --exclude=node_modules --exclude=.git

      - name: Archive Build Folder
        run: tar -czf backend.tar.gz -C /tmp/deployment-copy .

      # # Step 6: Install lftp
      # - name: Install lftp
      #   run: sudo apt-get install -y lftp
      # step 7  Deployment Steps
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.awrasacademy.org
          username: mallspot@mallspot.awrasacademy.org
          password: mallspot@123

      # Step 8: Deploy Build to Remote SSH Server
      # - name: Deploy with tar over SSH
      #   env:
      #     SSH_USERNAME: awrasaix
      #     SSH_HOST: 91.204.209.22
      #     SSH_PORT: 22
      #     REMOTE_PATH: ~/mallspot.awrasacademy.org/
      #   run: |
      #     # Ensure the SSH key is available
      #     echo "${{ secrets.SSH_PRIVATE }}" > private_key.pem
      #     chmod 600 private_key.pem

      #     # Run commands on the server
      #     ssh -i private_key.pem -p "$SSH_PORT" -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "
      #       cd /home/awrasaix/mallspot.awrasacademy.org &&
      #       cloudlinux-selector install-modules --json --interpreter nodejs --user awrasaix --app-root mallspot.awrasacademy.org"

      #     # Clean up the private key
      #     rm -f private_key.pem
